# Generated by Django 4.1.4 on 2022-12-30 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[(0, 'Pending'), (1, 'Delivered'), (2, 'Courier'), (3, 'Exchange'), (4, 'Cancel'), (5, 'Return')], default='Delivered', max_length=20)),
                ('invoice_no', models.IntegerField()),
                ('slug', models.SlugField(null=True, unique=True)),
                ('parcel_id', models.CharField(max_length=250)),
                ('customer_name', models.CharField(max_length=500)),
                ('customer_address', models.CharField(max_length=500)),
                ('customer_mobile', models.IntegerField()),
                ('delivary_charge', models.IntegerField()),
                ('tax', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=250, null=True)),
                ('code', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SizeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=6, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.productmodel')),
            ],
        ),
    ]
