# Generated by Django 4.1.4 on 2022-12-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemodel',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_quantity',
            field=models.IntegerField(),
        ),
    ]
