# Generated by Django 4.1.4 on 2022-12-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='slug',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='courier_type',
            field=models.CharField(choices=[('Pathao', 'Pathao'), ('RedX', 'RedX')], default='Pathao', max_length=10),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Courier', 'Courier'), ('Exchange', 'Exchange'), ('Cancel', 'Cancel'), ('Return', 'Return')], default='Delivered', max_length=20),
        ),
    ]
